### ISSUE TITLE
A Glitch in the Simulation

### ISSUE THREAD

**Issue by wiseaidev** [breakthecode2/neo#11]
The other day, I tried to use a couple of code using `runhacx`, and found that there is an bug when entering the code that starts with `M` and ends with `X`. The console gives the following error:

![Screenshot from 2022-03-30 09-15-48](https://user-images.githubusercontent.com/62179149/160767740-c8eb6197-4a63-47c3-ab1c-189f8b571363.png)

I am wondering why the server responded with `400` status code. Shouldn't it be 404 in case of code not found?

**Comment by radixdevs** [comment]
https://c.tenor.com/Y9WeTt9mNf8AAAAC/hmmm-thinking.gif

**Comment by radixdevs** [comment]
404 means page not found, 400 is the API telling you that your code is incorrect 🙂

**Comment by AaronDewes** [comment]
Hint: The thing that starts with M and ends with X is only part of the code.
