### ISSUE TITLE
Stop being `Vegan`

### ISSUE THREAD

**Issue by wiseaidev** [breakthecode2/neo#12]
I have just noticed that you pushed a new file named [`btc.config`](https://github.com/breakthecode2/neo/blob/main/btc.config) where you are supposed to configure `circleci` on the main branch, which is a cool exercise to work on. However, I saw that the `vegan`(just kidding, i mean `vigen...`) algo, especially with a key length=1, is being overused across the game. Thus, I would like to suggest using sha256 and changing your credentials to:

```sh
M2FlNmE0ODE5MDA2NjM0MjM2NmFkYjBiOGFlN2M5Yjk5NTdjM2MxMDQ1NGNjZjFiM2I1MzllNTMyNzliYzRiMw==
```

Have fun decoding it.

`Hint:` it is a url.

**Comment by Toby222** [comment]
You can't really decode a hash tho

**Comment by radixdevs** [comment]
https://uzs3svca.twic.pics/t/wrong/TATr9GU

**Comment by Harmouch101** [comment]
> You can't really decode a hash tho

But you can compare two hashes.
As mentioned in the hint, the plain text is a URL of a well known project about you know that I know that you know that never gonna...

lemme know If you have successfully found it.

Sincerely, Male Karen.
