### ISSUE TITLE
Not actual source code

### ISSUE THREAD

**Issue by ggtylerr** [breakthecode2/neo#17]
There is no code in this repo that runs cheat codes, excluding an HTML page with buttons that don't appear to do anything. Also, it's outdated. Therefore, I am now a karen and very angy, and immediately reporting this repo as malware!!!

**Comment by radixdevs** [comment]
https://c.tenor.com/xbOoUfZ8-KAAAAAC/oh-well-elmo.gif

**Comment by radixdevs** [comment]
You might wanna try using MALWARE as a cheat code... Might not work, might deduct 500pts... Risk it for a biscuit?! 🤷‍♂️

**Comment by jgmortim** [comment]
> You might wanna try using MALWARE as a cheat code... Might not work, might deduct 500pts... Risk it for a biscuit?! 🤷‍♂️

Bet

**Comment by ggtylerr** [comment]
![invalid cheatcode](https://user-images.githubusercontent.com/28498877/161179867-21b5123f-b3a9-410b-8c67-3102001c1d13.png)

Damn no points :( Can I have a biscuit now 🥺 

![I can't reach it :(](https://user-images.githubusercontent.com/28498877/161180277-ffa2706a-b232-4933-9baa-cb835d2b98d2.gif)

**Comment by radixdevs** [comment]
Sorry, too late... I already ate it

https://c.tenor.com/b_YO2KJ8pncAAAAC/doh-homer.gif

**Comment by ggtylerr** [comment]
😭
