### ISSUE TITLE
command doesn't work : gh repo clone breakthecode2/runhacx

### ISSUE THREAD

**Issue by HazardCodeBolt** [breakthecode2/neo#22]
gh repo clone breakthecode2/neo should be used instead

**Comment by taciturnaxolotl** [comment]
You have to enter the command into the breakthecode2 terminal. I had the same issue!

**Comment by b4ddr34m3r** [comment]
Aha, that works

**Comment by taciturnaxolotl** [comment]
Glad I can help!

**Comment by radixdevs** [comment]
https://media.giphy.com/media/e24Q8FKE2mxRS/giphy.gif
