### ISSUE TITLE
Why not?!

### ISSUE THREAD

**Issue by adamgede** [breakthecode2/neo#6]
How is SLVSPLRTE not a cheat code? It's a BOGO!
Sincerely,
Karen

**Comment by JonathanYeeW** [comment]
My thought exactly!

**Comment by justtei** [comment]
Are you Guys doing April Fool? xD

**Comment by itzlemo** [comment]
i'm calling the cops

**Comment by radixdevs** [comment]
https://c.tenor.com/oyuOsEqdT2wAAAAd/alan-partridge-banter.gif

**Comment by adamgede** [comment]
https://i.gifer.com/FBd6.gif
