### ISSUE TITLE
Open your web console brah

### ISSUE THREAD

**Issue by Harmouch101** [breakthecode2/neo#8]
Because of the ad/trackers blockers, i am currently using, i am not able to see the logs:

![Screenshot from 2022-03-28 23-32-26](https://user-images.githubusercontent.com/62179149/160482879-523ef193-2908-4b31-8f57-8785992462c1.png)

https://github.com/breakthecode2/neo/blob/01d61b9b06957b456da77bd5f686f4348f5cccb5/src/js/main.js#L35-L37

I am not willing to disable my ad blocker for privacy's sake. Can someone do a favor and look what's in there!

Thanks in advance.

**Comment by Harmouch101** [comment]
False positive!

**Comment by radixdevs** [comment]
https://c.tenor.com/7Ypq9_9najcAAAAd/thumbs-up-double-thumbs-up.gif
