### ISSUE TITLE
Install Command in Terminal 

### ISSUE THREAD

**Issue by jbarry376** [breakthecode2/neo#9]
The ```install [plugin]``` command in the breakthecode terminal is not working as expected. 
Running the command ```install test``` yields the same results as ```install RunHacx```. The same image and message about installing RunHacx shows up in the terminal no matter what plugin name is given.

**Comment by Harmouch101** [comment]
Same here, tried other commands, but all behave the same as `runhacx`:

```sh
install test
install common
install windows
install runhacx
```

Even tried cloning other repos:

```sh
gh repo clone breakthecode2/test
gh repo clone breakthecode2/common
gh repo clone breakthecode2/windows
gh repo clone breakthecode2/runhacx
```

**Comment by radixdevs** [comment]
Thanks for raising the issue, has been fixed

**Comment by radixdevs** [comment]
https://c.tenor.com/O3FkWgScIUMAAAAC/sponge-bob-thumbs-up.gif
